# Site settings
title: MB-Lab
email: rmantd.tg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mb-lab-community.github.io/MB-Lab.github.io/" # the base hostname & protocol for your site

twitter_username: 
github_username: animate1978
discord_server: https://discord.gg/FuJGcVN
forum_url: https://blenderartists.org/t/mb-lab-release-for-blender-2-80/1138777
patreon: https://www.patreon.com/mblab_development

# Downloads
build_version_slot1: 
build_version_slot2: 
build_version_slot3: 

# Build settings
markdown: kramdown


